# Generated by Django 5.1.6 on 2025-02-15 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=50, null=True, verbose_name='Улица')),
                ('house', models.CharField(blank=True, max_length=50, null=True, verbose_name='Дом')),
                ('apartment', models.CharField(blank=True, max_length=50, null=True, verbose_name='Квартира')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('registered_at', models.DateField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('registered_at', models.DateField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Продавец',
                'verbose_name_plural': 'Продавцы',
            },
        ),
        migrations.CreateModel(
            name='ShopsProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество, ед.')),
                ('price', models.PositiveBigIntegerField(help_text='Стоимость за единицу товара в копейках', verbose_name='Стоимость за ед.')),
                ('can_buy', models.BooleanField(verbose_name='Доступно для заказа')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autopurchases.product', verbose_name='Товары')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autopurchases.shop', verbose_name='Продавцы')),
            ],
            options={
                'verbose_name_plural': 'Каталог товаров',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='shops',
            field=models.ManyToManyField(related_name='products', through='autopurchases.ShopsProducts', to='autopurchases.shop'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество, ед.')),
                ('price', models.PositiveBigIntegerField(help_text='Стоимость за единицу товара в копейках', verbose_name='Стоимость за ед.')),
                ('total_price', models.PositiveBigIntegerField(help_text='Общая стоимость товаров в корзине', verbose_name='Общая стоимость')),
                ('status', models.CharField(choices=[('in_basket', 'В корзине'), ('created', 'Создан'), ('confirmed', 'Подтвержден'), ('assembled', 'Собран'), ('sent', 'Отправлен'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен')], default='in_basket', max_length=50, verbose_name='Статус заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autopurchases.customer', verbose_name='Покупатель')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autopurchases.shopsproducts', verbose_name='Товары')),
            ],
            options={
                'verbose_name_plural': 'Товары в корзине',
            },
        ),
    ]
