# Generated by Django 5.1.6 on 2025-03-10 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autopurchases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordresettoken',
            old_name='token',
            new_name='rtoken',
        ),
    ]
