# Generated by Django 5.1.6 on 2025-04-08 15:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autopurchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['id'], 'verbose_name': 'Products in cart', 'verbose_name_plural': 'Products in cart'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['id'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['id'], 'verbose_name': 'Shop', 'verbose_name_plural': 'Shops'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['id'], 'verbose_name': 'Products in stock', 'verbose_name_plural': 'Products in stock'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='rtoken',
            field=models.UUIDField(default=uuid.UUID('e1cc2495-0494-4667-b5f8-9d402291e3f0'), unique=True, verbose_name='Password reset token'),
        ),
        migrations.AlterField(
            model_name='product',
            name='parameters',
            field=models.ManyToManyField(through='autopurchases.ProductsParameters', to='autopurchases.parameter', verbose_name='Parameters'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Last name'),
        ),
    ]
