# Generated by Django 5.1.6 on 2025-03-06 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autopurchases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_info',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='autopurchases.contact', verbose_name='Адрес доставки'),
        ),
        migrations.DeleteModel(
            name='OrderInfo',
        ),
    ]
